apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "sre-reliability-lab.fullname" . }}
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "sre-reliability-lab.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
